spring:
  application:
    name: Social Media Service
  datasource:
    url: jdbc:postgresql://localhost:5432/social_media_db
    username: postgres
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_default: false
    open-in-view: false
